name: cgn-cpu
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - cpuonly=2.0
  - pytorch=1.10.0
  - torchvision=0.11.1
  - numpy==1.22
  - matplotlib==3.5.1
  - scipy==1.7.3
  - pandas==1.3.5
  - ipython=8.0.0
  - gdown==4.2
  - seaborn
  - scikit-learn
  - scipy
  - ipdb
  - jupyterlab
  - torchmetrics
  - tensorboardX==2.4
  - pip:
    - tqdm==4.62.3
    - repackage==0.7.3
    - yacs==0.1.8
    - pytorch-gradcam
    - gradio
    - natsort
    - kaggle==1.5.12
    - ipywidgets==7.6.5
